version: "3.4"

services:
  sql-server-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pa55w0rd12"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    expose:
      - 1433
  datingapp:
    image: ${DOCKER_REGISTRY-}datingapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - sql-server-db
